# Generated by Django 4.2.5 on 2023-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterstation',
            name='cardinal',
            field=models.CharField(choices=[('c', 'Central area'), ('n', 'North side'), ('s', 'South side'), ('e', 'East side'), ('w', 'West side')], default=None, max_length=1),
        ),
    ]
